### ISSUE TITLE
Acess denied for default user osticket on mariadb

### ISSUE THREAD

**Issue by shandshellin** [rinkp/osticket-dockerized#3]
I used the sample yml to deploy this stack, very minor changes for v3 compose. i get access denied warning for the default user and default password in the yml. I'll paste the yml and then the errors i see. I added path to bind the volumes but not much else changed.

```yaml
version: '3.6'
services:
  osticket:
    image: rinkp/osticket-dockerized:main
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - "OST_SECRET_SALT=" #<-- Fill in a random 256 bit key. Not provided in the example for safety
      - "OST_ADMIN_EMAIL=osticket@tech-i.ca"
      - "OST_ADMIN_PASSWD=osticket"
      - "OST_DBTYPE=mysql"
      - "OST_DBHOST=mariadb"
      - "OST_DBNAME=osticket"
      - "OST_DBUSER=osticket"
      - "OST_DBPASS=osticket"
      - "OST_TABLE_PREFIX=ost_"
      - "OST_TRUSTED_PROXIES=127.0.0.1"
      - "OST_LOCAL_NETWORKS=127.0.0.0/24"
      - "OST_SESSION_BACKEND=db"
      - "PHP_OPCACHE_MEMORY_CONSUMPTION=384"
      - "PHP_OPCACHE_MAX_WASTED_PERCENTAGE=10"
    restart: unless-stopped
    volumes:
      - /mnt/unixshare/Clusterstorage/etc/osticket:/var/www/attachments:rw
    networks:
      osticket-network:
        aliases:
          - osticket
    ports:
      - 0.0.0.0:8080:87/tcp
      
  mariadb:
    image: mariadb:latest
    environment:
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - "MARIADB_DATABASE=osticket"
      - "MARIADB_USER=osticket"
      - "MARIADB_PASSWORD=osticket"
      - "MARIADB_MYSQL_LOCALHOST_USER=yes"
    restart: unless-stopped
    volumes:
      - /mnt/unixshare/Clusterstorage/etc/osticket:/var/lib/mysql:rw
    healthcheck:
      test: "/usr/local/bin/healthcheck.sh --su mysql --connect --innodb_initialized"
      timeout: 10s
      retries: 5
    networks:
      osticket-network:
        aliases:
          - mariadb
    expose:
      - 3306
  
  #postfix:
  #  hostname: osticket-postfix
  #  image: juanluisbaptiste/postfix
  #  environment:
  #    - SMTP_SERVER=
  #    - SMTP_USERNAME=
  #    - SMTP_PASSWORD=
  #    - SMTP_PORT=587
  #    - SERVER_HOSTNAME=osticket-postfix
  #  restart: unless-stopped
  #  healthcheck:
  #    test: /bin/bash -c "if [ $$(mailq | wc -l) -ne 1 ]; then false; fi"
  #    interval: 1m
  #    timeout: 1s
  #    retries: 3
  #  stop_grace_period: 90s
  #  networks:
  #    osticket-network:
  #      aliases:
  #        - postfix
  #  expose:
  #    - "25"
        
networks:
  osticket-network:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
        
volumes:
  attachments:
  mysql:
```

### osticket_osticket
```
osticket_osticket.1.rqahcu5lbt6m@Cluster12    | Stack trace:
osticket_osticket.1.rqahcu5lbt6m@Cluster12    | #0 /var/www/html/include/mysqli.php(69): mysqli->real_connect()
osticket_osticket.1.rqahcu5lbt6m@Cluster12    | #1 /var/www/html/setup/inc/class.installer.php(94): db_connect()
osticket_osticket.1.rqahcu5lbt6m@Cluster12    | #2 /var/www/html/setup/envbasedinstall.php(35): Installer->install()
osticket_osticket.1.rqahcu5lbt6m@Cluster12    | #3 {main}
osticket_osticket.1.rqahcu5lbt6m@Cluster12    |   thrown in /var/www/html/include/mysqli.php on line 69
osticket_osticket.1.rqahcu5lbt6m@Cluster12    | PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'osticket'@'10.0.2.254' (using password: YES) in /var/www/html/include/mysqli.php:69
osticket_osticket.1.rqahcu5lbt6m@Cluster12    | Stack trace:
osticket_osticket.1.rqahcu5lbt6m@Cluster12    | #0 /var/www/html/include/mysqli.php(69): mysqli->real_connect()
osticket_osticket.1.rqahcu5lbt6m@Cluster12    | #1 /var/www/html/setup/inc/class.installer.php(94): db_connect()
osticket_osticket.1.rqahcu5lbt6m@Cluster12    | #2 /var/www/html/setup/envbasedinstall.php(35): Installer->install()
osticket_osticket.1.rqahcu5lbt6m@Cluster12    | #3 {main}
osticket_osticket.1.rqahcu5lbt6m@Cluster12    |   thrown in /var/www/html/include/mysqli.php on line 69
```

### osticket_mariadb

```
ree6@Cluster12    | 2024-02-09 18:13:06 117 [Warning] Access denied for user 'osticket'@'10.0.2.254' (using password: YES)
osticket_mariadb.1.eghypb1zree6@Cluster12    | 2024-02-09 18:13:14 118 [Warning] Access denied for user 'osticket'@'10.0.2.94' (using password: YES)
osticket_mariadb.1.eghypb1zree6@Cluster12    | 2024-02-09 18:13:22 119 [Warning] Access denied for user 'osticket'@'10.0.2.96' (using password: YES)
osticket_mariadb.1.eghypb1zree6@Cluster12    | 2024-02-09 18:13:30 120 [Warning] Access denied for user 'osticket'@'10.0.2.98' (using password: YES)
osticket_mariadb.1.eghypb1zree6@Cluster12    | 2024-02-09 18:13:35 121 [Warning] Access denied for user 'mysql'@'127.0.0.1' (using password: NO)
osticket_mariadb.1.eghypb1zree6@Cluster12    | 2024-02-09 18:13:38 123 [Warning] Access denied for user 'osticket'@'10.0.2.254' (using password: YES)
osticket_mariadb.1.eghypb1zree6@Cluster12    | 2024-02-09 18:13:45 124 [Warning] Access denied for user 'osticket'@'10.0.2.101' (using password: YES)
osticket_mariadb.1.eghypb1zree6@Cluster12    | 2024-02-09 18:13:52 125 [Warning] Access denied for user 'osticket'@'10.0.2.103' (using password: YES)
osticket_mariadb.1.eghypb1zree6@Cluster12    | 2024-02-09 18:13:59 126 [Warning] Access denied for user 'osticket'@'10.0.2.254' (using password: YES)
osticket_mariadb.1.eghypb1zree6@Cluster12    | 2024-02-09 18:14:06 127 [Warning] Access denied for user 'mysql'@'127.0.0.1' (using password: NO)
osticket_mariadb.1.eghypb1zree6@Cluster12    | 2024-02-09 18:14:06 129 [Warning] Access denied for user 'osticket'@'10.0.2.254' (using password: YES)
osticket_mariadb.1.eghypb1zree6@Cluster12    | 2024-02-09 18:14:14 130 [Warning] Access denied for user 'osticket'@'10.0.2.107' (using password: YES)
osticket_mariadb.1.eghypb1zree6@Cluster12    | 2024-02-09 18:14:26 131 [Warning] Access denied for user 'osticket'@'10.0.2.109' (using password: YES)
osticket_mariadb.1.eghypb1zree6@Cluster12    | 2024-02-09 18:14:36 132 [Warning] Access denied for user 'mysql'@'127.0.0.1' (using password: NO)
osticket_mariadb.1.eghypb1zree6@Cluster12    | 2024-02-09 18:14:36 134 [Warning] Access denied for user 'osticket'@'10.0.2.111' (using password: YES)
```

**Comment by rinkp** [comment]
It seems like you are mounting the same folder on two different paths in your configuration. Most likely this causes mariadb to not perform well

**Comment by shandshellin** [comment]
Made the change giving it it's own folder. same issue

```
osticket_mariadb.1.qlgt8s7a4zak@Cluster8    | 2024-02-09 18:49:06 141 [Warning] Access denied for user 'osticket'@'10.0.2.103' (using password: YES)
osticket_mariadb.1.qlgt8s7a4zak@Cluster8    | 2024-02-09 18:49:14 142 [Warning] Access denied for user 'osticket'@'10.0.2.105' (using password: YES)
osticket_mariadb.1.qlgt8s7a4zak@Cluster8    | 2024-02-09 18:49:21 143 [Warning] Access denied for user 'osticket'@'10.0.2.177' (using password: YES)
```

```
osticket_osticket.1.jn6y21y76u0c@Cluster9    | Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'osticket'@'10.0.2.110' (using password: YES) in /var/www/html/include/mysqli.php:69
osticket_osticket.1.jn6y21y76u0c@Cluster9    | Stack trace:
osticket_osticket.1.jn6y21y76u0c@Cluster9    | #0 /var/www/html/include/mysqli.php(69): mysqli->real_connect()
osticket_osticket.1.jn6y21y76u0c@Cluster9    | #1 /var/www/html/setup/inc/class.installer.php(94): db_connect()
osticket_osticket.1.jn6y21y76u0c@Cluster9    | #2 /var/www/html/setup/envbasedinstall.php(35): Installer->install()
osticket_osticket.1.jn6y21y76u0c@Cluster9    | #3 {main}
osticket_osticket.1.jn6y21y76u0c@Cluster9    |   thrown in /var/www/html/include/mysqli.php on line 69
```

**Comment by rinkp** [comment]
Please make sure you start mariadb with an empty volume (and not the possibly corrupted one from before). Once you do, the server will initialize itself first. Make sure that these steps are performed correctly. 
If the osticket user does not work correctly, could you verify whether sign-ins are possible with the root user that is then generated and outputted on first startup (see below for an example)

Please also note that for production use, you can connect any instance of a database server. You do not have to use the included mariadb container.

```
2024-02-09 19:55:03 2024-02-09 18:55:03+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.2.2+maria~ubu2204 started.
2024-02-09 19:55:04 2024-02-09 18:55:04+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2024-02-09 19:55:04 2024-02-09 18:55:04+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.2.2+maria~ubu2204 started.
2024-02-09 19:55:04 2024-02-09 18:55:04+00:00 [Note] [Entrypoint]: Initializing database files
2024-02-09 19:55:07 
2024-02-09 19:55:07 
2024-02-09 19:55:07 PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
2024-02-09 19:55:07 To do so, start the server, then issue the following command:
2024-02-09 19:55:07 
2024-02-09 19:55:07 '/usr/bin/mariadb-secure-installation'
2024-02-09 19:55:07 
2024-02-09 19:55:07 which will also give you the option of removing the test
2024-02-09 19:55:07 databases and anonymous user created by default.  This is
2024-02-09 19:55:07 strongly recommended for production servers.
2024-02-09 19:55:07 
2024-02-09 19:55:07 See the MariaDB Knowledgebase at https://mariadb.com/kb
2024-02-09 19:55:07 
2024-02-09 19:55:07 Please report any problems at https://mariadb.org/jira
2024-02-09 19:55:07 
2024-02-09 19:55:07 The latest information about MariaDB is available at https://mariadb.org/.
2024-02-09 19:55:07 
2024-02-09 19:55:07 Consider joining MariaDB's strong and vibrant community:
2024-02-09 19:55:07 https://mariadb.org/get-involved/
2024-02-09 19:55:07 
2024-02-09 19:55:07 2024-02-09 18:55:07+00:00 [Note] [Entrypoint]: Database files initialized
2024-02-09 19:55:07 2024-02-09 18:55:07+00:00 [Note] [Entrypoint]: Starting temporary server
2024-02-09 19:55:07 2024-02-09 18:55:07+00:00 [Note] [Entrypoint]: Waiting for server startup
2024-02-09 19:55:08 2024-02-09 18:55:08+00:00 [Note] [Entrypoint]: Temporary server started.
2024-02-09 19:55:11 2024-02-09 18:55:11+00:00 [Note] [Entrypoint]: GENERATED ROOT PASSWORD: ABCDEFGHIJKLMNOPQRSTUVWXYZ
2024-02-09 19:55:11 2024-02-09 18:55:11+00:00 [Note] [Entrypoint]: Creating database osticket
2024-02-09 19:55:11 2024-02-09 18:55:11+00:00 [Note] [Entrypoint]: Creating user osticket
2024-02-09 19:55:11 2024-02-09 18:55:11+00:00 [Note] [Entrypoint]: Giving user osticket access to schema osticket
2024-02-09 19:55:11 2024-02-09 18:55:11+00:00 [Note] [Entrypoint]: Securing system users (equivalent to running mysql_secure_installation)
2024-02-09 19:55:11 
2024-02-09 19:55:11 2024-02-09 18:55:11+00:00 [Note] [Entrypoint]: Stopping temporary server
2024-02-09 19:55:11 2024-02-09 18:55:11+00:00 [Note] [Entrypoint]: Temporary server stopped
2024-02-09 19:55:11 
2024-02-09 19:55:11 2024-02-09 18:55:11+00:00 [Note] [Entrypoint]: MariaDB init process done. Ready for start up.
2024-02-09 19:55:11 
```

**Comment by shandshellin** [comment]
noticed this int he output, user is oticket not osticket?

2024-02-09 19:17:36+00:00 [Note] [Entrypoint]: Temporary server started.
2024-02-09 19:17:44+00:00 [Note] [Entrypoint]: GENERATED ROOT PASSWORD: V@jh+yiB{my4H$uvQ:w%Zx/LU5f#6l4/
2024-02-09 19:17:44+00:00 [Note] [Entrypoint]: Creating database osticket
2024-02-09 19:17:44+00:00 [Note] [Entrypoint]: Creating user oticket
2024-02-09 19:17:44+00:00 [Note] [Entrypoint]: Giving user oticket access to schema osticket
2024-02-09 19:17:44+00:00 [Note] [Entrypoint]: Securing system users (equivalent to running mysql_secure_installation)
2024-02-09 19:17:44+00:00 [Note] [Entrypoint]: Stopping temporary server

**Comment by shandshellin** [comment]
here is the complete log

2024-02-09 19:17:02+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.2.2+maria~ubu2204 started.
2024-02-09 19:17:03+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2024-02-09 19:17:03+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.2.2+maria~ubu2204 started.
2024-02-09 19:17:04+00:00 [Note] [Entrypoint]: Initializing database files
PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following command:
'/usr/bin/mariadb-secure-installation'
which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.
See the MariaDB Knowledgebase at https://mariadb.com/kb
Please report any problems at https://mariadb.org/jira
The latest information about MariaDB is available at https://mariadb.org/.
Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/
2024-02-09 19:17:35+00:00 [Note] [Entrypoint]: Database files initialized
2024-02-09 19:17:35+00:00 [Note] [Entrypoint]: Starting temporary server
2024-02-09 19:17:35+00:00 [Note] [Entrypoint]: Waiting for server startup
2024-02-09 19:17:35 0 [Note] Starting MariaDB 11.2.2-MariaDB-1:11.2.2+maria~ubu2204 source revision 929532a9426d085111c24c63de9c23cc54382259 as process 111
2024-02-09 19:17:36 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2024-02-09 19:17:36 0 [Note] InnoDB: Number of transaction pools: 1
2024-02-09 19:17:36 0 [Note] InnoDB: Using ARMv8 crc32 instructions
2024-02-09 19:17:36 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
2024-02-09 19:17:36 0 [Note] InnoDB: Using liburing
2024-02-09 19:17:36 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2024-02-09 19:17:36 0 [Note] InnoDB: Completed initialization of buffer pool
2024-02-09 19:17:36 0 [Note] InnoDB: Buffered log writes (block size=512 bytes)
2024-02-09 19:17:36 0 [Note] InnoDB: End of log at LSN=47629
2024-02-09 19:17:36 0 [Note] InnoDB: Opened 3 undo tablespaces
2024-02-09 19:17:36 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
2024-02-09 19:17:36 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
2024-02-09 19:17:36 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
2024-02-09 19:17:36 0 [Note] InnoDB: log sequence number 47629; transaction id 14
2024-02-09 19:17:36 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-02-09 19:17:36 0 [Note] Plugin 'wsrep-provider' is disabled.
2024-02-09 19:17:36 0 [Warning] 'user' entry 'root@66d867d4ca48' ignored in --skip-name-resolve mode.
2024-02-09 19:17:36 0 [Warning] 'proxies_priv' entry '@% root@66d867d4ca48' ignored in --skip-name-resolve mode.
2024-02-09 19:17:36 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
2024-02-09 19:17:36 0 [Note] mariadbd: ready for connections.
Version: '11.2.2-MariaDB-1:11.2.2+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
2024-02-09 19:17:36+00:00 [Note] [Entrypoint]: Temporary server started.
2024-02-09 19:17:44+00:00 [Note] [Entrypoint]: GENERATED ROOT PASSWORD: V@jh+yiB{my4H$uvQ:w%Zx/LU5f#6l4/
2024-02-09 19:17:44+00:00 [Note] [Entrypoint]: Creating database osticket
2024-02-09 19:17:44+00:00 [Note] [Entrypoint]: Creating user oticket
2024-02-09 19:17:44+00:00 [Note] [Entrypoint]: Giving user oticket access to schema osticket
2024-02-09 19:17:44+00:00 [Note] [Entrypoint]: Securing system users (equivalent to running mysql_secure_installation)
2024-02-09 19:17:44+00:00 [Note] [Entrypoint]: Stopping temporary server
2024-02-09 19:17:44 0 [Note] mariadbd (initiated by: unknown): Normal shutdown
2024-02-09 19:17:44 0 [Note] InnoDB: FTS optimize thread exiting.
2024-02-09 19:17:45 0 [Note] InnoDB: Starting shutdown...
2024-02-09 19:17:45 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2024-02-09 19:17:45 0 [Note] InnoDB: Buffer pool(s) dump completed at 240209 19:17:45
2024-02-09 19:17:45 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2024-02-09 19:17:45 0 [Note] InnoDB: Shutdown completed; log sequence number 47629; transaction id 15
2024-02-09 19:17:45 0 [Note] mariadbd: Shutdown complete
2024-02-09 19:17:45+00:00 [Note] [Entrypoint]: Temporary server stopped
2024-02-09 19:17:45+00:00 [Note] [Entrypoint]: MariaDB init process done. Ready for start up.
2024-02-09 19:17:45 0 [Note] Starting MariaDB 11.2.2-MariaDB-1:11.2.2+maria~ubu2204 source revision 929532a9426d085111c24c63de9c23cc54382259 as process 1
2024-02-09 19:17:45 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2024-02-09 19:17:45 0 [Note] InnoDB: Number of transaction pools: 1
2024-02-09 19:17:45 0 [Note] InnoDB: Using ARMv8 crc32 instructions
2024-02-09 19:17:45 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
2024-02-09 19:17:45 0 [Note] InnoDB: Using liburing
2024-02-09 19:17:45 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2024-02-09 19:17:45 0 [Note] InnoDB: Completed initialization of buffer pool
2024-02-09 19:17:45 0 [Note] InnoDB: Buffered log writes (block size=512 bytes)
2024-02-09 19:17:45 0 [Note] InnoDB: End of log at LSN=47629
2024-02-09 19:17:46 0 [Note] InnoDB: Opened 3 undo tablespaces
2024-02-09 19:17:46 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
2024-02-09 19:17:46 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
2024-02-09 19:17:46 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
2024-02-09 19:17:46 0 [Note] InnoDB: log sequence number 47629; transaction id 14
2024-02-09 19:17:46 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-02-09 19:17:46 0 [Note] Plugin 'wsrep-provider' is disabled.
2024-02-09 19:17:46 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2024-02-09 19:17:46 0 [Note] InnoDB: Buffer pool(s) load completed at 240209 19:17:46
2024-02-09 19:17:46 0 [Note] Server socket created on IP: '0.0.0.0'.
2024-02-09 19:17:46 0 [Note] Server socket created on IP: '::'.
2024-02-09 19:17:46 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
2024-02-09 19:17:46 0 [Note] mariadbd: ready for connections.
Version: '11.2.2-MariaDB-1:11.2.2+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2024-02-09 19:18:02 3 [Warning] Access denied for user 'mysql'@'127.0.0.1' (using password: NO)
2024-02-09 19:18:06 5 [Warning] Access denied for user 'osticket'@'10.0.2.22' (using password: YES)

**Comment by shandshellin** [comment]
shyould i be using "root" as the user for the root password in both maria and osticket env variables?

**Comment by rinkp** [comment]
> noticed this int he output, user is oticket not osticket?

Unless you have found a very specific bug in [MariaDB](https://github.com/MariaDB/server) I think this suggests a typo in your `docker-compose.yml`

Since this is the issue, you **don´t have to try** signing in as root. That would only be for debugging and in your case would use username `root` and password `V@jh+yiB{my4H$uvQ:w%Zx/LU5f#6l4/` but only on the osticket-side. 

Closing this issue since it is either an issue with your compose configuration (highly likely) or an issue with mariadb where they randomly drop letters from environment variables (not so likely)

**Comment by shandshellin** [comment]
root works but the output i posted was generated from the script that ran at first time boot. It clearly named the user osticket to oticket in the output. Is that not a mistake in the script?

 [Entrypoint]: Creating user oticket

**Comment by rinkp** [comment]
> Is that not a mistake in the script?

Your output `[Entrypoint]: Creating user oticket` is output from the container mariadb. Please be aware that I am not the maintainer of mariadb, nor did I create the entrypoint script for it.

If your `docker-compose.yaml` has `MARIADB_USER=osticket` and not `MARIADB_USER=oticket`, then this can be an issue in mariadb, but [their script](https://github.com/MariaDB/mariadb-docker/blob/master/docker-entrypoint.sh#L417) does nothing else than simply using the environment variable, so I think the most likely cause for your issues is a typo made by you when first running the mariadb container. [Nobody has reported an issue for the user of MARIADB_USER with the `mariadb:latest` container on GitHub.](https://github.com/MariaDB/mariadb-docker/issues?q=is%3Aissue+mariadb_user+is%3Aclosed)

```yaml
  mariadb:
    image: mariadb:latest
    environment:
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - "MARIADB_DATABASE=osticket"
      - "MARIADB_USER=osticket"
      - "MARIADB_PASSWORD=osticket"
      - "MARIADB_MYSQL_LOCALHOST_USER=yes"
```
Also, the example does not have a spelling mistake, so it is unclear what you expect from me at this point.
